/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package restserver;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.glassfish.grizzly.http.server.HttpServer;
import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;
import org.glassfish.jersey.server.ResourceConfig;
import restserver.GameConfig;

public class GameGrizzlyApp {

    private static URI BASE_URI = URI.create("http://localhost:8080/");

    public static HttpServer startServer(int waitSecondsForServer) throws IOException {
        final URI baseUri = (BASE_URI);
        final ResourceConfig resourceConfig = (new GameConfig());
        final HttpServer httpServer = GrizzlyHttpServerFactory.createHttpServer(baseUri, resourceConfig);
        if (waitSecondsForServer < 0) {
            return httpServer;
        }
        while (waitSecondsForServer > 0) {
            try {
                final URL clientUrl = new URL(baseUri + "game");
                final HttpURLConnection connection = (HttpURLConnection) clientUrl.openConnection();
                final int responseCode = connection.getResponseCode();
                System.out.println("Trying " + clientUrl + ": " + responseCode);
                connection.disconnect();
                if (responseCode == 200) {
                    return httpServer;
                }
            } catch (final Exception e) {
            }
            try {
                Thread.sleep(1000);
                waitSecondsForServer -= 1;
            } catch (final InterruptedException e) {
                return null;
            }
        }
        return null;
    }

    public static void stopServer(final HttpServer server) throws IOException {
        server.shutdown();
    }

    public static void main(final String[] args) throws IOException {
        try {
            final HttpServer server = startServer( -1);
            Runtime.getRuntime().addShutdownHook(new Thread(server::shutdownNow));
            Thread.currentThread().join();
        } catch (final InterruptedException ex) {
            Logger.getLogger(GameGrizzlyApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
