const AT = {
    //START GAME
    START_GAME_REQUESTED: 'START_GAME_REQUESTED',
    START_GAME_RECIEVED: 'START_GAME_RECIEVED',
    START_GAME_FAILED: 'START_GAME_FAILED',

    //SET NAME
    SET_NAME_REQUESTED: 'SET_NAME_REQUESTED',
    SET_NAME_RECIEVED: 'SET_NAME_RECIEVED',
    SET_NAME_FAILED: 'SET_NAME_FAILED',

    //SELECT OPPONENT
    SELECT_OPPONENT_REQUESTED: 'SELECT_OPPONENT_REQUESTED',
    SELECT_OPPONENT_RECIEVED: 'SELECT_OPPONENT_RECIEVED',
    SELECT_OPPONENT_FAILED: 'SELECT_OPPONENT_FAILED',

    //CLICK SQUARE
    CLICK_SQUARE_REQUESTED: 'CLICK_SQUARE_REQUESTED',
    CLICK_SQUARE_RECIEVED: 'CLICK_SQUARE_RECIEVED',
    CLICK_SQUARE_FAILED: 'CLICK_SQUARE_FAILED'
}

export default AT